[package]
name = "oentike"
autobins = false
version = "0.1.1"
description = "Oentike desktop application"
authors = ["Oentike contributors"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.71"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "oentike_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[[bin]]
name = "Oentike"
path = "src/main.rs"

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.11.5", features = [] }
tauri-plugin-log = "2.9.0"

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }
