[package]
name = "oentike"
version = "0.1.0"
description = "Oentike desktop application"
authors = ["Oentike contributors"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.71"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "oentike_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.11.5", features = [] }
tauri-plugin-log = "2.9.0"

tonic = { version = "0.12", features = ["tls"] }
prost = "0.13"
tokio = { version = "1.40", features = ["macros", "rt-multi-thread"] }
sysinfo = "0.30"
async-nats = "0.45.0"
futures = "0.3.34"

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }
tonic-build = "0.12"
