// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: fingate.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MtlsSetupMs   int64                  `protobuf:"varint,1,opt,name=mtls_setup_ms,json=mtlsSetupMs,proto3" json:"mtls_setup_ms,omitempty"`
	PayloadBytes  int32                  `protobuf:"varint,2,opt,name=payload_bytes,json=payloadBytes,proto3" json:"payload_bytes,omitempty"`
	Region        string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMetrics) Reset() {
	*x = ClientMetrics{}
	mi := &file_fingate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMetrics) ProtoMessage() {}

func (x *ClientMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_fingate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMetrics.ProtoReflect.Descriptor instead.
func (*ClientMetrics) Descriptor() ([]byte, []int) {
	return file_fingate_proto_rawDescGZIP(), []int{0}
}

func (x *ClientMetrics) GetMtlsSetupMs() int64 {
	if x != nil {
		return x.MtlsSetupMs
	}
	return 0
}

func (x *ClientMetrics) GetPayloadBytes() int32 {
	if x != nil {
		return x.PayloadBytes
	}
	return 0
}

func (x *ClientMetrics) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

type TelemetryRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AgentId         string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	CpuUsagePercent float32                `protobuf:"fixed32,2,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`
	MemoryUsedMb    int32                  `protobuf:"varint,3,opt,name=memory_used_mb,json=memoryUsedMb,proto3" json:"memory_used_mb,omitempty"`
	Metrics         *ClientMetrics         `protobuf:"bytes,4,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TelemetryRequest) Reset() {
	*x = TelemetryRequest{}
	mi := &file_fingate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryRequest) ProtoMessage() {}

func (x *TelemetryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fingate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryRequest.ProtoReflect.Descriptor instead.
func (*TelemetryRequest) Descriptor() ([]byte, []int) {
	return file_fingate_proto_rawDescGZIP(), []int{1}
}

func (x *TelemetryRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *TelemetryRequest) GetCpuUsagePercent() float32 {
	if x != nil {
		return x.CpuUsagePercent
	}
	return 0
}

func (x *TelemetryRequest) GetMemoryUsedMb() int32 {
	if x != nil {
		return x.MemoryUsedMb
	}
	return 0
}

func (x *TelemetryRequest) GetMetrics() *ClientMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type TelemetryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryResponse) Reset() {
	*x = TelemetryResponse{}
	mi := &file_fingate_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryResponse) ProtoMessage() {}

func (x *TelemetryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fingate_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryResponse.ProtoReflect.Descriptor instead.
func (*TelemetryResponse) Descriptor() ([]byte, []int) {
	return file_fingate_proto_rawDescGZIP(), []int{2}
}

func (x *TelemetryResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_fingate_proto protoreflect.FileDescriptor

const file_fingate_proto_rawDesc = "" +
	"\n" +
	"\rfingate.proto\x12\x0foentike.fingate\"p\n" +
	"\rClientMetrics\x12\"\n" +
	"\rmtls_setup_ms\x18\x01 \x01(\x03R\vmtlsSetupMs\x12#\n" +
	"\rpayload_bytes\x18\x02 \x01(\x05R\fpayloadBytes\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\"\xb9\x01\n" +
	"\x10TelemetryRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12*\n" +
	"\x11cpu_usage_percent\x18\x02 \x01(\x02R\x0fcpuUsagePercent\x12$\n" +
	"\x0ememory_used_mb\x18\x03 \x01(\x05R\fmemoryUsedMb\x128\n" +
	"\ametrics\x18\x04 \x01(\v2\x1e.oentike.fingate.ClientMetricsR\ametrics\"+\n" +
	"\x11TelemetryResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2l\n" +
	"\x0eFingateService\x12Z\n" +
	"\x0fStreamTelemetry\x12!.oentike.fingate.TelemetryRequest\x1a\".oentike.fingate.TelemetryResponse(\x01B\x1eZ\x1coentike-control-plane/api/v1b\x06proto3"

var (
	file_fingate_proto_rawDescOnce sync.Once
	file_fingate_proto_rawDescData []byte
)

func file_fingate_proto_rawDescGZIP() []byte {
	file_fingate_proto_rawDescOnce.Do(func() {
		file_fingate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fingate_proto_rawDesc), len(file_fingate_proto_rawDesc)))
	})
	return file_fingate_proto_rawDescData
}

var file_fingate_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_fingate_proto_goTypes = []any{
	(*ClientMetrics)(nil),     // 0: oentike.fingate.ClientMetrics
	(*TelemetryRequest)(nil),  // 1: oentike.fingate.TelemetryRequest
	(*TelemetryResponse)(nil), // 2: oentike.fingate.TelemetryResponse
}
var file_fingate_proto_depIdxs = []int32{
	0, // 0: oentike.fingate.TelemetryRequest.metrics:type_name -> oentike.fingate.ClientMetrics
	1, // 1: oentike.fingate.FingateService.StreamTelemetry:input_type -> oentike.fingate.TelemetryRequest
	2, // 2: oentike.fingate.FingateService.StreamTelemetry:output_type -> oentike.fingate.TelemetryResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_fingate_proto_init() }
func file_fingate_proto_init() {
	if File_fingate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fingate_proto_rawDesc), len(file_fingate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fingate_proto_goTypes,
		DependencyIndexes: file_fingate_proto_depIdxs,
		MessageInfos:      file_fingate_proto_msgTypes,
	}.Build()
	File_fingate_proto = out.File
	file_fingate_proto_goTypes = nil
	file_fingate_proto_depIdxs = nil
}
