// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: fingate.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FingateService_GetUsage_FullMethodName    = "/oentike.fingate.FingateService/GetUsage"
	FingateService_StreamUsage_FullMethodName = "/oentike.fingate.FingateService/StreamUsage"
)

// FingateServiceClient is the client API for FingateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FingateServiceClient interface {
	GetUsage(ctx context.Context, in *UsageRequest, opts ...grpc.CallOption) (*UsageResponse, error)
	StreamUsage(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UsageRequest, UsageResponse], error)
}

type fingateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFingateServiceClient(cc grpc.ClientConnInterface) FingateServiceClient {
	return &fingateServiceClient{cc}
}

func (c *fingateServiceClient) GetUsage(ctx context.Context, in *UsageRequest, opts ...grpc.CallOption) (*UsageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UsageResponse)
	err := c.cc.Invoke(ctx, FingateService_GetUsage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fingateServiceClient) StreamUsage(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UsageRequest, UsageResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FingateService_ServiceDesc.Streams[0], FingateService_StreamUsage_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UsageRequest, UsageResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FingateService_StreamUsageClient = grpc.ClientStreamingClient[UsageRequest, UsageResponse]

// FingateServiceServer is the server API for FingateService service.
// All implementations must embed UnimplementedFingateServiceServer
// for forward compatibility.
type FingateServiceServer interface {
	GetUsage(context.Context, *UsageRequest) (*UsageResponse, error)
	StreamUsage(grpc.ClientStreamingServer[UsageRequest, UsageResponse]) error
	mustEmbedUnimplementedFingateServiceServer()
}

// UnimplementedFingateServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFingateServiceServer struct{}

func (UnimplementedFingateServiceServer) GetUsage(context.Context, *UsageRequest) (*UsageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUsage not implemented")
}
func (UnimplementedFingateServiceServer) StreamUsage(grpc.ClientStreamingServer[UsageRequest, UsageResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamUsage not implemented")
}
func (UnimplementedFingateServiceServer) mustEmbedUnimplementedFingateServiceServer() {}
func (UnimplementedFingateServiceServer) testEmbeddedByValue()                        {}

// UnsafeFingateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FingateServiceServer will
// result in compilation errors.
type UnsafeFingateServiceServer interface {
	mustEmbedUnimplementedFingateServiceServer()
}

func RegisterFingateServiceServer(s grpc.ServiceRegistrar, srv FingateServiceServer) {
	// If the following call panics, it indicates UnimplementedFingateServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FingateService_ServiceDesc, srv)
}

func _FingateService_GetUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FingateServiceServer).GetUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FingateService_GetUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FingateServiceServer).GetUsage(ctx, req.(*UsageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FingateService_StreamUsage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FingateServiceServer).StreamUsage(&grpc.GenericServerStream[UsageRequest, UsageResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FingateService_StreamUsageServer = grpc.ClientStreamingServer[UsageRequest, UsageResponse]

// FingateService_ServiceDesc is the grpc.ServiceDesc for FingateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FingateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "oentike.fingate.FingateService",
	HandlerType: (*FingateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUsage",
			Handler:    _FingateService_GetUsage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamUsage",
			Handler:       _FingateService_StreamUsage_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "fingate.proto",
}
