// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: fingate.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountName   string                 `protobuf:"bytes,1,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	Value         int64                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	TransactionId int32                  `protobuf:"varint,4,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionRequest) Reset() {
	*x = TransactionRequest{}
	mi := &file_fingate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionRequest) ProtoMessage() {}

func (x *TransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fingate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionRequest.ProtoReflect.Descriptor instead.
func (*TransactionRequest) Descriptor() ([]byte, []int) {
	return file_fingate_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionRequest) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *TransactionRequest) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *TransactionRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *TransactionRequest) GetTransactionId() int32 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

type UsageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CPU           string                 `protobuf:"bytes,1,opt,name=CPU,proto3" json:"CPU,omitempty"`
	Memory        string                 `protobuf:"bytes,2,opt,name=Memory,proto3" json:"Memory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsageResponse) Reset() {
	*x = UsageResponse{}
	mi := &file_fingate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageResponse) ProtoMessage() {}

func (x *UsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fingate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageResponse.ProtoReflect.Descriptor instead.
func (*UsageResponse) Descriptor() ([]byte, []int) {
	return file_fingate_proto_rawDescGZIP(), []int{1}
}

func (x *UsageResponse) GetCPU() string {
	if x != nil {
		return x.CPU
	}
	return ""
}

func (x *UsageResponse) GetMemory() string {
	if x != nil {
		return x.Memory
	}
	return ""
}

type UsageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsageRequest) Reset() {
	*x = UsageRequest{}
	mi := &file_fingate_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageRequest) ProtoMessage() {}

func (x *UsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fingate_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageRequest.ProtoReflect.Descriptor instead.
func (*UsageRequest) Descriptor() ([]byte, []int) {
	return file_fingate_proto_rawDescGZIP(), []int{2}
}

func (x *UsageRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

var File_fingate_proto protoreflect.FileDescriptor

const file_fingate_proto_rawDesc = "" +
	"\n" +
	"\rfingate.proto\x12\x0foentike.fingate\"\x90\x01\n" +
	"\x12TransactionRequest\x12!\n" +
	"\faccount_name\x18\x01 \x01(\tR\vaccountName\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12%\n" +
	"\x0etransaction_id\x18\x04 \x01(\x05R\rtransactionId\"9\n" +
	"\rUsageResponse\x12\x10\n" +
	"\x03CPU\x18\x01 \x01(\tR\x03CPU\x12\x16\n" +
	"\x06Memory\x18\x02 \x01(\tR\x06Memory\")\n" +
	"\fUsageRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId2\xab\x01\n" +
	"\x0eFingateService\x12I\n" +
	"\bGetUsage\x12\x1d.oentike.fingate.UsageRequest\x1a\x1e.oentike.fingate.UsageResponse\x12N\n" +
	"\vStreamUsage\x12\x1d.oentike.fingate.UsageRequest\x1a\x1e.oentike.fingate.UsageResponse(\x01B\x1eZ\x1coentike-control-plane/api/v1b\x06proto3"

var (
	file_fingate_proto_rawDescOnce sync.Once
	file_fingate_proto_rawDescData []byte
)

func file_fingate_proto_rawDescGZIP() []byte {
	file_fingate_proto_rawDescOnce.Do(func() {
		file_fingate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fingate_proto_rawDesc), len(file_fingate_proto_rawDesc)))
	})
	return file_fingate_proto_rawDescData
}

var file_fingate_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_fingate_proto_goTypes = []any{
	(*TransactionRequest)(nil), // 0: oentike.fingate.TransactionRequest
	(*UsageResponse)(nil),      // 1: oentike.fingate.UsageResponse
	(*UsageRequest)(nil),       // 2: oentike.fingate.UsageRequest
}
var file_fingate_proto_depIdxs = []int32{
	2, // 0: oentike.fingate.FingateService.GetUsage:input_type -> oentike.fingate.UsageRequest
	2, // 1: oentike.fingate.FingateService.StreamUsage:input_type -> oentike.fingate.UsageRequest
	1, // 2: oentike.fingate.FingateService.GetUsage:output_type -> oentike.fingate.UsageResponse
	1, // 3: oentike.fingate.FingateService.StreamUsage:output_type -> oentike.fingate.UsageResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fingate_proto_init() }
func file_fingate_proto_init() {
	if File_fingate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fingate_proto_rawDesc), len(file_fingate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fingate_proto_goTypes,
		DependencyIndexes: file_fingate_proto_depIdxs,
		MessageInfos:      file_fingate_proto_msgTypes,
	}.Build()
	File_fingate_proto = out.File
	file_fingate_proto_goTypes = nil
	file_fingate_proto_depIdxs = nil
}
