// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.32.1
// source: fingate.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FingateService_StreamTelemetry_FullMethodName = "/oentike.fingate.FingateService/StreamTelemetry"
)

// FingateServiceClient is the client API for FingateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FingateServiceClient interface {
	StreamTelemetry(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[TelemetryRequest, TelemetryResponse], error)
}

type fingateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFingateServiceClient(cc grpc.ClientConnInterface) FingateServiceClient {
	return &fingateServiceClient{cc}
}

func (c *fingateServiceClient) StreamTelemetry(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[TelemetryRequest, TelemetryResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FingateService_ServiceDesc.Streams[0], FingateService_StreamTelemetry_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TelemetryRequest, TelemetryResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FingateService_StreamTelemetryClient = grpc.ClientStreamingClient[TelemetryRequest, TelemetryResponse]

// FingateServiceServer is the server API for FingateService service.
// All implementations must embed UnimplementedFingateServiceServer
// for forward compatibility.
type FingateServiceServer interface {
	StreamTelemetry(grpc.ClientStreamingServer[TelemetryRequest, TelemetryResponse]) error
	mustEmbedUnimplementedFingateServiceServer()
}

// UnimplementedFingateServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFingateServiceServer struct{}

func (UnimplementedFingateServiceServer) StreamTelemetry(grpc.ClientStreamingServer[TelemetryRequest, TelemetryResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamTelemetry not implemented")
}
func (UnimplementedFingateServiceServer) mustEmbedUnimplementedFingateServiceServer() {}
func (UnimplementedFingateServiceServer) testEmbeddedByValue()                        {}

// UnsafeFingateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FingateServiceServer will
// result in compilation errors.
type UnsafeFingateServiceServer interface {
	mustEmbedUnimplementedFingateServiceServer()
}

func RegisterFingateServiceServer(s grpc.ServiceRegistrar, srv FingateServiceServer) {
	// If the following call panics, it indicates UnimplementedFingateServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FingateService_ServiceDesc, srv)
}

func _FingateService_StreamTelemetry_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FingateServiceServer).StreamTelemetry(&grpc.GenericServerStream[TelemetryRequest, TelemetryResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FingateService_StreamTelemetryServer = grpc.ClientStreamingServer[TelemetryRequest, TelemetryResponse]

// FingateService_ServiceDesc is the grpc.ServiceDesc for FingateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FingateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "oentike.fingate.FingateService",
	HandlerType: (*FingateServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamTelemetry",
			Handler:       _FingateService_StreamTelemetry_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "fingate.proto",
}
