package main

// ---

import (
	// Standard libraries
    "context"
    "fmt"
    "log"
    "net"

    // Generated by protoc and protoc-gen-go
    pb "oentike-control-plane/api/v1"
    "google.golang.org/grpc"
)

// ---

// Structs
type server struct {
    pb.UnimplementedFingateServiceServer
}

// GetUsage returns the usage information for the agent
func (s *server) GetUsage(ctx context.Context, req *pb.UsageRequest) (*pb.UsageResponse, error) {
    log.Printf("🔒 Otrzymano połączenie od agenta: %s", req.GetAgentId())
    return &pb.UsageResponse{
        CPU:    "Zarejestrowano (Control Plane)",
        Memory: "Zarejestrowano (Control Plane)",
    }, nil
}

// main is the entry point of our server
func main() {
    lis, err := net.Listen("tcp", ":50051")
    if err != nil {
        log.Fatalf("Nie udało się otworzyć portu: %v", err)
    }

    s := grpc.NewServer()

    pb.RegisterFingateServiceServer(s, &server{})
    fmt.Println("🚀 ZT-FinGate Control Plane nasłuchuje na porcie 50051...")

    if err := s.Serve(lis); err != nil {
        log.Fatalf("Błąd serwera gRPC: %v", err)
    }
}
