// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0
// source: conditions.proto

package conditionsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetConditionsRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	CellId      string                 `protobuf:"bytes,1,opt,name=cell_id,json=cellId,proto3" json:"cell_id,omitempty"`
	SpeciesSlug string                 `protobuf:"bytes,2,opt,name=species_slug,json=speciesSlug,proto3" json:"species_slug,omitempty"`
	// Civil date YYYY-MM-DD in Europe/Warsaw. Empty means today.
	TargetDate    string `protobuf:"bytes,3,opt,name=target_date,json=targetDate,proto3" json:"target_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConditionsRequest) Reset() {
	*x = GetConditionsRequest{}
	mi := &file_conditions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConditionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConditionsRequest) ProtoMessage() {}

func (x *GetConditionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conditions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConditionsRequest.ProtoReflect.Descriptor instead.
func (*GetConditionsRequest) Descriptor() ([]byte, []int) {
	return file_conditions_proto_rawDescGZIP(), []int{0}
}

func (x *GetConditionsRequest) GetCellId() string {
	if x != nil {
		return x.CellId
	}
	return ""
}

func (x *GetConditionsRequest) GetSpeciesSlug() string {
	if x != nil {
		return x.SpeciesSlug
	}
	return ""
}

func (x *GetConditionsRequest) GetTargetDate() string {
	if x != nil {
		return x.TargetDate
	}
	return ""
}

type Factor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Unit          string                 `protobuf:"bytes,2,opt,name=unit,proto3" json:"unit,omitempty"`
	Value         *float64               `protobuf:"fixed64,3,opt,name=value,proto3,oneof" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Factor) Reset() {
	*x = Factor{}
	mi := &file_conditions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Factor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Factor) ProtoMessage() {}

func (x *Factor) ProtoReflect() protoreflect.Message {
	mi := &file_conditions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Factor.ProtoReflect.Descriptor instead.
func (*Factor) Descriptor() ([]byte, []int) {
	return file_conditions_proto_rawDescGZIP(), []int{1}
}

func (x *Factor) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Factor) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *Factor) GetValue() float64 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

type ConditionsResponse struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	CellId      string                 `protobuf:"bytes,1,opt,name=cell_id,json=cellId,proto3" json:"cell_id,omitempty"`
	CellName    string                 `protobuf:"bytes,2,opt,name=cell_name,json=cellName,proto3" json:"cell_name,omitempty"`
	SpeciesSlug string                 `protobuf:"bytes,3,opt,name=species_slug,json=speciesSlug,proto3" json:"species_slug,omitempty"`
	TargetDate  string                 `protobuf:"bytes,4,opt,name=target_date,json=targetDate,proto3" json:"target_date,omitempty"`
	// ready | unavailable - business status, not the gRPC code.
	Status           string    `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Score            *int32    `protobuf:"varint,6,opt,name=score,proto3,oneof" json:"score,omitempty"`
	Confidence       string    `protobuf:"bytes,7,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Factors          []*Factor `protobuf:"bytes,8,rep,name=factors,proto3" json:"factors,omitempty"`
	AlgorithmVersion string    `protobuf:"bytes,9,opt,name=algorithm_version,json=algorithmVersion,proto3" json:"algorithm_version,omitempty"`
	InputSha256      *string   `protobuf:"bytes,10,opt,name=input_sha256,json=inputSha256,proto3,oneof" json:"input_sha256,omitempty"`
	// Latest Open-Meteo ingest for this cell (RFC3339). Empty if none.
	FetchedAt     *string `protobuf:"bytes,11,opt,name=fetched_at,json=fetchedAt,proto3,oneof" json:"fetched_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConditionsResponse) Reset() {
	*x = ConditionsResponse{}
	mi := &file_conditions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConditionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConditionsResponse) ProtoMessage() {}

func (x *ConditionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_conditions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConditionsResponse.ProtoReflect.Descriptor instead.
func (*ConditionsResponse) Descriptor() ([]byte, []int) {
	return file_conditions_proto_rawDescGZIP(), []int{2}
}

func (x *ConditionsResponse) GetCellId() string {
	if x != nil {
		return x.CellId
	}
	return ""
}

func (x *ConditionsResponse) GetCellName() string {
	if x != nil {
		return x.CellName
	}
	return ""
}

func (x *ConditionsResponse) GetSpeciesSlug() string {
	if x != nil {
		return x.SpeciesSlug
	}
	return ""
}

func (x *ConditionsResponse) GetTargetDate() string {
	if x != nil {
		return x.TargetDate
	}
	return ""
}

func (x *ConditionsResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ConditionsResponse) GetScore() int32 {
	if x != nil && x.Score != nil {
		return *x.Score
	}
	return 0
}

func (x *ConditionsResponse) GetConfidence() string {
	if x != nil {
		return x.Confidence
	}
	return ""
}

func (x *ConditionsResponse) GetFactors() []*Factor {
	if x != nil {
		return x.Factors
	}
	return nil
}

func (x *ConditionsResponse) GetAlgorithmVersion() string {
	if x != nil {
		return x.AlgorithmVersion
	}
	return ""
}

func (x *ConditionsResponse) GetInputSha256() string {
	if x != nil && x.InputSha256 != nil {
		return *x.InputSha256
	}
	return ""
}

func (x *ConditionsResponse) GetFetchedAt() string {
	if x != nil && x.FetchedAt != nil {
		return *x.FetchedAt
	}
	return ""
}

type GetSeasonRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	CellId      string                 `protobuf:"bytes,1,opt,name=cell_id,json=cellId,proto3" json:"cell_id,omitempty"`
	SpeciesSlug string                 `protobuf:"bytes,2,opt,name=species_slug,json=speciesSlug,proto3" json:"species_slug,omitempty"`
	// Inclusive day count ending today (Europe/Warsaw). 0 means 9. Max 14.
	Days          int32 `protobuf:"varint,3,opt,name=days,proto3" json:"days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSeasonRequest) Reset() {
	*x = GetSeasonRequest{}
	mi := &file_conditions_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeasonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeasonRequest) ProtoMessage() {}

func (x *GetSeasonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conditions_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeasonRequest.ProtoReflect.Descriptor instead.
func (*GetSeasonRequest) Descriptor() ([]byte, []int) {
	return file_conditions_proto_rawDescGZIP(), []int{3}
}

func (x *GetSeasonRequest) GetCellId() string {
	if x != nil {
		return x.CellId
	}
	return ""
}

func (x *GetSeasonRequest) GetSpeciesSlug() string {
	if x != nil {
		return x.SpeciesSlug
	}
	return ""
}

func (x *GetSeasonRequest) GetDays() int32 {
	if x != nil {
		return x.Days
	}
	return 0
}

type SeasonDay struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Score         *int32                 `protobuf:"varint,3,opt,name=score,proto3,oneof" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeasonDay) Reset() {
	*x = SeasonDay{}
	mi := &file_conditions_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeasonDay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeasonDay) ProtoMessage() {}

func (x *SeasonDay) ProtoReflect() protoreflect.Message {
	mi := &file_conditions_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeasonDay.ProtoReflect.Descriptor instead.
func (*SeasonDay) Descriptor() ([]byte, []int) {
	return file_conditions_proto_rawDescGZIP(), []int{4}
}

func (x *SeasonDay) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *SeasonDay) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SeasonDay) GetScore() int32 {
	if x != nil && x.Score != nil {
		return *x.Score
	}
	return 0
}

type SeasonResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CellId           string                 `protobuf:"bytes,1,opt,name=cell_id,json=cellId,proto3" json:"cell_id,omitempty"`
	CellName         string                 `protobuf:"bytes,2,opt,name=cell_name,json=cellName,proto3" json:"cell_name,omitempty"`
	SpeciesSlug      string                 `protobuf:"bytes,3,opt,name=species_slug,json=speciesSlug,proto3" json:"species_slug,omitempty"`
	AlgorithmVersion string                 `protobuf:"bytes,4,opt,name=algorithm_version,json=algorithmVersion,proto3" json:"algorithm_version,omitempty"`
	Days             []*SeasonDay           `protobuf:"bytes,5,rep,name=days,proto3" json:"days,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SeasonResponse) Reset() {
	*x = SeasonResponse{}
	mi := &file_conditions_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeasonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeasonResponse) ProtoMessage() {}

func (x *SeasonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_conditions_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeasonResponse.ProtoReflect.Descriptor instead.
func (*SeasonResponse) Descriptor() ([]byte, []int) {
	return file_conditions_proto_rawDescGZIP(), []int{5}
}

func (x *SeasonResponse) GetCellId() string {
	if x != nil {
		return x.CellId
	}
	return ""
}

func (x *SeasonResponse) GetCellName() string {
	if x != nil {
		return x.CellName
	}
	return ""
}

func (x *SeasonResponse) GetSpeciesSlug() string {
	if x != nil {
		return x.SpeciesSlug
	}
	return ""
}

func (x *SeasonResponse) GetAlgorithmVersion() string {
	if x != nil {
		return x.AlgorithmVersion
	}
	return ""
}

func (x *SeasonResponse) GetDays() []*SeasonDay {
	if x != nil {
		return x.Days
	}
	return nil
}

type SearchCellsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Empty returns cells ordered by name (up to limit).
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// 0 means 20. Max 20.
	Limit         int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchCellsRequest) Reset() {
	*x = SearchCellsRequest{}
	mi := &file_conditions_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchCellsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchCellsRequest) ProtoMessage() {}

func (x *SearchCellsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conditions_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchCellsRequest.ProtoReflect.Descriptor instead.
func (*SearchCellsRequest) Descriptor() ([]byte, []int) {
	return file_conditions_proto_rawDescGZIP(), []int{6}
}

func (x *SearchCellsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchCellsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type CellSummary struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Centroid in WGS84.
	Lon float64 `protobuf:"fixed64,3,opt,name=lon,proto3" json:"lon,omitempty"`
	Lat float64 `protobuf:"fixed64,4,opt,name=lat,proto3" json:"lat,omitempty"`
	// Bounding box in WGS84 for the map frame.
	West          float64 `protobuf:"fixed64,5,opt,name=west,proto3" json:"west,omitempty"`
	South         float64 `protobuf:"fixed64,6,opt,name=south,proto3" json:"south,omitempty"`
	East          float64 `protobuf:"fixed64,7,opt,name=east,proto3" json:"east,omitempty"`
	North         float64 `protobuf:"fixed64,8,opt,name=north,proto3" json:"north,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CellSummary) Reset() {
	*x = CellSummary{}
	mi := &file_conditions_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CellSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CellSummary) ProtoMessage() {}

func (x *CellSummary) ProtoReflect() protoreflect.Message {
	mi := &file_conditions_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CellSummary.ProtoReflect.Descriptor instead.
func (*CellSummary) Descriptor() ([]byte, []int) {
	return file_conditions_proto_rawDescGZIP(), []int{7}
}

func (x *CellSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CellSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CellSummary) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *CellSummary) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *CellSummary) GetWest() float64 {
	if x != nil {
		return x.West
	}
	return 0
}

func (x *CellSummary) GetSouth() float64 {
	if x != nil {
		return x.South
	}
	return 0
}

func (x *CellSummary) GetEast() float64 {
	if x != nil {
		return x.East
	}
	return 0
}

func (x *CellSummary) GetNorth() float64 {
	if x != nil {
		return x.North
	}
	return 0
}

type SearchCellsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cells         []*CellSummary         `protobuf:"bytes,1,rep,name=cells,proto3" json:"cells,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchCellsResponse) Reset() {
	*x = SearchCellsResponse{}
	mi := &file_conditions_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchCellsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchCellsResponse) ProtoMessage() {}

func (x *SearchCellsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_conditions_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchCellsResponse.ProtoReflect.Descriptor instead.
func (*SearchCellsResponse) Descriptor() ([]byte, []int) {
	return file_conditions_proto_rawDescGZIP(), []int{8}
}

func (x *SearchCellsResponse) GetCells() []*CellSummary {
	if x != nil {
		return x.Cells
	}
	return nil
}

type EnsureCellRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CellId        string                 `protobuf:"bytes,1,opt,name=cell_id,json=cellId,proto3" json:"cell_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureCellRequest) Reset() {
	*x = EnsureCellRequest{}
	mi := &file_conditions_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureCellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureCellRequest) ProtoMessage() {}

func (x *EnsureCellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conditions_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureCellRequest.ProtoReflect.Descriptor instead.
func (*EnsureCellRequest) Descriptor() ([]byte, []int) {
	return file_conditions_proto_rawDescGZIP(), []int{9}
}

func (x *EnsureCellRequest) GetCellId() string {
	if x != nil {
		return x.CellId
	}
	return ""
}

type EnsureCellResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cell          *CellSummary           `protobuf:"bytes,1,opt,name=cell,proto3" json:"cell,omitempty"`
	Ingested      bool                   `protobuf:"varint,2,opt,name=ingested,proto3" json:"ingested,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureCellResponse) Reset() {
	*x = EnsureCellResponse{}
	mi := &file_conditions_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureCellResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureCellResponse) ProtoMessage() {}

func (x *EnsureCellResponse) ProtoReflect() protoreflect.Message {
	mi := &file_conditions_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureCellResponse.ProtoReflect.Descriptor instead.
func (*EnsureCellResponse) Descriptor() ([]byte, []int) {
	return file_conditions_proto_rawDescGZIP(), []int{10}
}

func (x *EnsureCellResponse) GetCell() *CellSummary {
	if x != nil {
		return x.Cell
	}
	return nil
}

func (x *EnsureCellResponse) GetIngested() bool {
	if x != nil {
		return x.Ingested
	}
	return false
}

var File_conditions_proto protoreflect.FileDescriptor

const file_conditions_proto_rawDesc = "" +
	"\n" +
	"\x10conditions.proto\x12\x12oentike.conditions\"s\n" +
	"\x14GetConditionsRequest\x12\x17\n" +
	"\acell_id\x18\x01 \x01(\tR\x06cellId\x12!\n" +
	"\fspecies_slug\x18\x02 \x01(\tR\vspeciesSlug\x12\x1f\n" +
	"\vtarget_date\x18\x03 \x01(\tR\n" +
	"targetDate\"Q\n" +
	"\x06Factor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04unit\x18\x02 \x01(\tR\x04unit\x12\x19\n" +
	"\x05value\x18\x03 \x01(\x01H\x00R\x05value\x88\x01\x01B\b\n" +
	"\x06_value\"\xba\x03\n" +
	"\x12ConditionsResponse\x12\x17\n" +
	"\acell_id\x18\x01 \x01(\tR\x06cellId\x12\x1b\n" +
	"\tcell_name\x18\x02 \x01(\tR\bcellName\x12!\n" +
	"\fspecies_slug\x18\x03 \x01(\tR\vspeciesSlug\x12\x1f\n" +
	"\vtarget_date\x18\x04 \x01(\tR\n" +
	"targetDate\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x19\n" +
	"\x05score\x18\x06 \x01(\x05H\x00R\x05score\x88\x01\x01\x12\x1e\n" +
	"\n" +
	"confidence\x18\a \x01(\tR\n" +
	"confidence\x124\n" +
	"\afactors\x18\b \x03(\v2\x1a.oentike.conditions.FactorR\afactors\x12+\n" +
	"\x11algorithm_version\x18\t \x01(\tR\x10algorithmVersion\x12&\n" +
	"\finput_sha256\x18\n" +
	" \x01(\tH\x01R\vinputSha256\x88\x01\x01\x12\"\n" +
	"\n" +
	"fetched_at\x18\v \x01(\tH\x02R\tfetchedAt\x88\x01\x01B\b\n" +
	"\x06_scoreB\x0f\n" +
	"\r_input_sha256B\r\n" +
	"\v_fetched_at\"b\n" +
	"\x10GetSeasonRequest\x12\x17\n" +
	"\acell_id\x18\x01 \x01(\tR\x06cellId\x12!\n" +
	"\fspecies_slug\x18\x02 \x01(\tR\vspeciesSlug\x12\x12\n" +
	"\x04days\x18\x03 \x01(\x05R\x04days\"\\\n" +
	"\tSeasonDay\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x19\n" +
	"\x05score\x18\x03 \x01(\x05H\x00R\x05score\x88\x01\x01B\b\n" +
	"\x06_score\"\xc9\x01\n" +
	"\x0eSeasonResponse\x12\x17\n" +
	"\acell_id\x18\x01 \x01(\tR\x06cellId\x12\x1b\n" +
	"\tcell_name\x18\x02 \x01(\tR\bcellName\x12!\n" +
	"\fspecies_slug\x18\x03 \x01(\tR\vspeciesSlug\x12+\n" +
	"\x11algorithm_version\x18\x04 \x01(\tR\x10algorithmVersion\x121\n" +
	"\x04days\x18\x05 \x03(\v2\x1d.oentike.conditions.SeasonDayR\x04days\"@\n" +
	"\x12SearchCellsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\xa9\x01\n" +
	"\vCellSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03lon\x18\x03 \x01(\x01R\x03lon\x12\x10\n" +
	"\x03lat\x18\x04 \x01(\x01R\x03lat\x12\x12\n" +
	"\x04west\x18\x05 \x01(\x01R\x04west\x12\x14\n" +
	"\x05south\x18\x06 \x01(\x01R\x05south\x12\x12\n" +
	"\x04east\x18\a \x01(\x01R\x04east\x12\x14\n" +
	"\x05north\x18\b \x01(\x01R\x05north\"L\n" +
	"\x13SearchCellsResponse\x125\n" +
	"\x05cells\x18\x01 \x03(\v2\x1f.oentike.conditions.CellSummaryR\x05cells\",\n" +
	"\x11EnsureCellRequest\x12\x17\n" +
	"\acell_id\x18\x01 \x01(\tR\x06cellId\"e\n" +
	"\x12EnsureCellResponse\x123\n" +
	"\x04cell\x18\x01 \x01(\v2\x1f.oentike.conditions.CellSummaryR\x04cell\x12\x1a\n" +
	"\bingested\x18\x02 \x01(\bR\bingested2\x8a\x03\n" +
	"\x11ConditionsService\x12a\n" +
	"\rGetConditions\x12(.oentike.conditions.GetConditionsRequest\x1a&.oentike.conditions.ConditionsResponse\x12U\n" +
	"\tGetSeason\x12$.oentike.conditions.GetSeasonRequest\x1a\".oentike.conditions.SeasonResponse\x12^\n" +
	"\vSearchCells\x12&.oentike.conditions.SearchCellsRequest\x1a'.oentike.conditions.SearchCellsResponse\x12[\n" +
	"\n" +
	"EnsureCell\x12%.oentike.conditions.EnsureCellRequest\x1a&.oentike.conditions.EnsureCellResponseB#Z!oentike-api/internal/conditionsv1b\x06proto3"

var (
	file_conditions_proto_rawDescOnce sync.Once
	file_conditions_proto_rawDescData []byte
)

func file_conditions_proto_rawDescGZIP() []byte {
	file_conditions_proto_rawDescOnce.Do(func() {
		file_conditions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_conditions_proto_rawDesc), len(file_conditions_proto_rawDesc)))
	})
	return file_conditions_proto_rawDescData
}

var file_conditions_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_conditions_proto_goTypes = []any{
	(*GetConditionsRequest)(nil), // 0: oentike.conditions.GetConditionsRequest
	(*Factor)(nil),               // 1: oentike.conditions.Factor
	(*ConditionsResponse)(nil),   // 2: oentike.conditions.ConditionsResponse
	(*GetSeasonRequest)(nil),     // 3: oentike.conditions.GetSeasonRequest
	(*SeasonDay)(nil),            // 4: oentike.conditions.SeasonDay
	(*SeasonResponse)(nil),       // 5: oentike.conditions.SeasonResponse
	(*SearchCellsRequest)(nil),   // 6: oentike.conditions.SearchCellsRequest
	(*CellSummary)(nil),          // 7: oentike.conditions.CellSummary
	(*SearchCellsResponse)(nil),  // 8: oentike.conditions.SearchCellsResponse
	(*EnsureCellRequest)(nil),    // 9: oentike.conditions.EnsureCellRequest
	(*EnsureCellResponse)(nil),   // 10: oentike.conditions.EnsureCellResponse
}
var file_conditions_proto_depIdxs = []int32{
	1,  // 0: oentike.conditions.ConditionsResponse.factors:type_name -> oentike.conditions.Factor
	4,  // 1: oentike.conditions.SeasonResponse.days:type_name -> oentike.conditions.SeasonDay
	7,  // 2: oentike.conditions.SearchCellsResponse.cells:type_name -> oentike.conditions.CellSummary
	7,  // 3: oentike.conditions.EnsureCellResponse.cell:type_name -> oentike.conditions.CellSummary
	0,  // 4: oentike.conditions.ConditionsService.GetConditions:input_type -> oentike.conditions.GetConditionsRequest
	3,  // 5: oentike.conditions.ConditionsService.GetSeason:input_type -> oentike.conditions.GetSeasonRequest
	6,  // 6: oentike.conditions.ConditionsService.SearchCells:input_type -> oentike.conditions.SearchCellsRequest
	9,  // 7: oentike.conditions.ConditionsService.EnsureCell:input_type -> oentike.conditions.EnsureCellRequest
	2,  // 8: oentike.conditions.ConditionsService.GetConditions:output_type -> oentike.conditions.ConditionsResponse
	5,  // 9: oentike.conditions.ConditionsService.GetSeason:output_type -> oentike.conditions.SeasonResponse
	8,  // 10: oentike.conditions.ConditionsService.SearchCells:output_type -> oentike.conditions.SearchCellsResponse
	10, // 11: oentike.conditions.ConditionsService.EnsureCell:output_type -> oentike.conditions.EnsureCellResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_conditions_proto_init() }
func file_conditions_proto_init() {
	if File_conditions_proto != nil {
		return
	}
	file_conditions_proto_msgTypes[1].OneofWrappers = []any{}
	file_conditions_proto_msgTypes[2].OneofWrappers = []any{}
	file_conditions_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_conditions_proto_rawDesc), len(file_conditions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_conditions_proto_goTypes,
		DependencyIndexes: file_conditions_proto_depIdxs,
		MessageInfos:      file_conditions_proto_msgTypes,
	}.Build()
	File_conditions_proto = out.File
	file_conditions_proto_goTypes = nil
	file_conditions_proto_depIdxs = nil
}
