// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v7.36.0
// source: conditions.proto

package conditionsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConditionsService_GetConditions_FullMethodName = "/oentike.conditions.ConditionsService/GetConditions"
)

// ConditionsServiceClient is the client API for ConditionsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ConditionsService is the product query surface. Health stays on HTTP;
// this RPC is the conditions contract (gRPC now, SPIFFE/mTLS later).
type ConditionsServiceClient interface {
	GetConditions(ctx context.Context, in *GetConditionsRequest, opts ...grpc.CallOption) (*ConditionsResponse, error)
}

type conditionsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConditionsServiceClient(cc grpc.ClientConnInterface) ConditionsServiceClient {
	return &conditionsServiceClient{cc}
}

func (c *conditionsServiceClient) GetConditions(ctx context.Context, in *GetConditionsRequest, opts ...grpc.CallOption) (*ConditionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConditionsResponse)
	err := c.cc.Invoke(ctx, ConditionsService_GetConditions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConditionsServiceServer is the server API for ConditionsService service.
// All implementations must embed UnimplementedConditionsServiceServer
// for forward compatibility.
//
// ConditionsService is the product query surface. Health stays on HTTP;
// this RPC is the conditions contract (gRPC now, SPIFFE/mTLS later).
type ConditionsServiceServer interface {
	GetConditions(context.Context, *GetConditionsRequest) (*ConditionsResponse, error)
	mustEmbedUnimplementedConditionsServiceServer()
}

// UnimplementedConditionsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConditionsServiceServer struct{}

func (UnimplementedConditionsServiceServer) GetConditions(context.Context, *GetConditionsRequest) (*ConditionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConditions not implemented")
}
func (UnimplementedConditionsServiceServer) mustEmbedUnimplementedConditionsServiceServer() {}
func (UnimplementedConditionsServiceServer) testEmbeddedByValue()                           {}

// UnsafeConditionsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConditionsServiceServer will
// result in compilation errors.
type UnsafeConditionsServiceServer interface {
	mustEmbedUnimplementedConditionsServiceServer()
}

func RegisterConditionsServiceServer(s grpc.ServiceRegistrar, srv ConditionsServiceServer) {
	// If the following call panics, it indicates UnimplementedConditionsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConditionsService_ServiceDesc, srv)
}

func _ConditionsService_GetConditions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConditionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConditionsServiceServer).GetConditions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConditionsService_GetConditions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConditionsServiceServer).GetConditions(ctx, req.(*GetConditionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConditionsService_ServiceDesc is the grpc.ServiceDesc for ConditionsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConditionsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "oentike.conditions.ConditionsService",
	HandlerType: (*ConditionsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConditions",
			Handler:    _ConditionsService_GetConditions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "conditions.proto",
}
