const entries = {
    title: ["Oentike — Wyprawa", "Oentike — Expedition"],
    eyebrow: ["W TERENIE", "IN THE FIELD"],
    heading: ["Ślad prowadzi z powrotem.", "Your trail leads back."],
    lead: ["Zapisz parking i zbieraj ślad wyprawy. Wszystko pozostaje na tym urządzeniu.", "Save your parking spot and record your trail. Everything stays on this device."],
    local: ["Dziennik lokalny", "Local journal"],
    newTrip: ["Nowa wyprawa", "New expedition"],
    name: ["Nazwa wyprawy", "Expedition name"],
    latitude: ["Szerokość geograficzna", "Latitude"],
    longitude: ["Długość geograficzna", "Longitude"],
    locate: ["Wstaw obecną lokalizację", "Use current location"],
    create: ["Zapisz parking i utwórz wyprawę", "Save parking and create expedition"],
    parkingHint: ["Wpisz współrzędne parkingu lub pobierz je z urządzenia. Parking pozostaje stałym punktem tej wyprawy.", "Enter parking coordinates or get them from your device. Parking stays fixed for this expedition."],
    trips: ["Twoje wyprawy", "Your expeditions"],
    choose: ["Wybierz wyprawę", "Choose expedition"],
    empty: ["Zapisz parking, aby rozpocząć.", "Save a parking spot to begin."],
    start: ["Rejestruj ślad", "Record trail"],
    pause: ["Wstrzymaj", "Pause"],
    export: ["Eksportuj GeoJSON", "Export GeoJSON"],
    diagram: ["Szkic śladu · północ u góry", "Trail sketch · north up"],
    diagramHint: ["Szkic bez podkładu mapowego. Przerwy w pomiarach pozostają przerwami. Linia nie potwierdza drożności terenu.", "Sketch without a basemap. Measurement gaps stay disconnected. A line does not confirm traversable terrain."],
    trail: ["Zarejestrowany dystans", "Recorded distance"],
    direct: ["Do parkingu w linii prostej", "Straight-line distance to parking"],
    azimuth: ["Azymut do parkingu", "Bearing to parking"],
    samples: ["Zapisane próbki", "Saved samples"],
    last: ["Ostatni zapis", "Last saved"],
    accuracy: ["Dokładność ostatniej próbki", "Last sample accuracy"],
    parking: ["Parking", "Parking"],
    lastPoint: ["Ostatni punkt", "Last point"],
    metricsHint: ["Dystanse są przybliżone i mogą zawierać dryf lokalizacji. Azymut liczony jest od ostatniego zapisu względem północy geograficznej — to nie kompas ani wyznaczona trasa.", "Distances are estimates and may include location drift. Bearing is measured from the last saved point relative to true north — it is not a compass or a routed path."],
    foreground: ["Rejestracja działa przy otwartym, widocznym ekranie wyprawy. Ukrycie okna, zmiana strony lub restart przerywa rejestrację; wznów ją przyciskiem.", "Recording works while this expedition screen is open and visible. Hiding the window, changing pages or restarting interrupts recording; resume with the button."],
    privacy: ["Dane są lokalne, bez dodatkowego szyfrowania. Wyczyszczenie danych aplikacji lub przeglądarki usuwa dziennik. Eksport zawiera dokładne współrzędne.", "Data is local, without additional encryption. Clearing app or browser data removes the journal. Exports include precise coordinates."],
    loading: ["Otwieranie dziennika…", "Opening journal…"],
    ready: ["Dziennik gotowy. Rejestracja wstrzymana.", "Journal ready. Recording paused."],
    saved: ["Parking zapisany. Możesz rozpocząć rejestrację.", "Parking saved. You can start recording."],
    locating: ["Oczekiwanie na lokalizację…", "Waiting for location…"],
    located: ["Lokalizacja wpisana. Zapisz parking, aby ją zachować.", "Location filled in. Save parking to keep it."],
    recording: ["Rejestracja aktywna. Próbki są zapisywane co najmniej 5 sekund od siebie.", "Recording active. Samples are saved at least 5 seconds apart."],
    paused: ["Rejestracja wstrzymana. Zatwierdzone próbki pozostają zapisane.", "Recording paused. Committed samples remain saved."],
    hidden: ["Ekran został ukryty. Rejestracja wstrzymana — wznów ją ręcznie.", "Screen was hidden. Recording paused — resume manually."],
    poor: ["Pomiar pominięty: dokładność gorsza niż 100 m lub nieaktualna lokalizacja.", "Sample skipped: accuracy worse than 100 m or stale location."],
    permission: ["Brak zgody na lokalizację. Zezwól na nią w ustawieniach urządzenia lub przeglądarki.", "Location permission denied. Enable it in device or browser settings."],
    unavailable: ["Lokalizacja niedostępna. Parking możesz wpisać ręcznie; rejestracja wymaga lokalizacji urządzenia.", "Location unavailable. You can enter parking manually; recording requires device location."],
    timeout: ["Nie uzyskano lokalizacji na czas. Spróbuj ponownie.", "Location request timed out. Try again."],
    storage: ["Nie udało się odczytać lub zapisać dziennika. Rejestracja zatrzymana. Sprawdź dostępne miejsce i dostęp do danych lokalnych.", "Could not read or save the journal. Recording stopped. Check free space and local storage access."],
    invalidPoint: ["Sprawdź współrzędne: szerokość −90…90, długość −180…180.", "Check coordinates: latitude −90…90, longitude −180…180."],
    limit: ["Osiągnięto limit 100 000 próbek wyprawy. Wyeksportuj ślad i utwórz nową wyprawę.", "This expedition reached 100,000 samples. Export the trail and create a new expedition."],
    oldPoint: ["Pominięto pomiar starszy od ostatniego zapisu. Sprawdź zegar urządzenia.", "Skipped a sample older than the last saved point. Check the device clock."],
    nameError: ["Podaj nazwę wyprawy (1–80 znaków).", "Enter an expedition name (1–80 characters)."],
    persist: ["Chroń zapis przed automatycznym usuwaniem", "Protect storage from automatic eviction"],
    persistent: ["Urządzenie przyznało trwałe przechowywanie. Nadal warto eksportować wyprawy.", "Device granted persistent storage. Exporting expeditions is still recommended."],
    bestEffort: ["Urządzenie nie przyznało trwałego przechowywania. Zachowuj kopie eksportów.", "Device did not grant persistent storage. Keep exported backups."],
};
export const fieldText = (key, language = "pl") => entries[key]?.[language.startsWith("en") ? 1 : 0] || key;
