[package]
name = "oentike-edge-agent"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = { version = "0.12", features = ["tls"] }
prost = "0.13"
tokio = { version = "1.40", features = ["macros", "rt-multi-thread"] }
iced = { version = "0.12", default-features = false, features = ["tokio", "fira-sans"] }
spiffe = { version = "0.16.0", features = ["workload-api-x509"] }
pem = "4.0.0"
sysinfo = "0.30"
tokio-stream = "0.1"

[build-dependencies]
tonic-build = "0.12"
